Picon.py: Replace unicode() with str()
Decode back to str with ASCII decoding to fix:

File "/usr/lib/enigma2/python/Components/Renderer/Picon.py", line 92, in getPiconName
    name = re.sub('[^a-z0-9]', '', name.replace('&', 'and').replace('+', 'plus').replace('*', 'star').lower())
TypeError: a bytes-like object is required, not 'str'